blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
format_strings = true
hard_tabs = true
imports_indent = "Block"
imports_layout = "Horizontal"
match_block_trailing_comma = true
max_width = 180
merge_imports = true
normalize_comments = true
reorder_impl_items = true
reorder_imports = true
struct_lit_single_line = true
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
